"""The standalone terminal's spot universe.

The stock list is derived from Fyers' official NSE derivatives instrument
master on 25 September 2026 (instrument type 13, stock futures). It deliberately
excludes derivative indices because the four requested index spots are maintained
separately below.
"""

INDEX_SPOTS = {
    "NIFTY": "NSE:NIFTY50-INDEX",
    "SENSEX": "BSE:SENSEX-INDEX",
    "BANKNIFTY": "NSE:NIFTYBANK-INDEX",
    "MIDCPNIFTY": "NSE:MIDCPNIFTY-INDEX",
}

FNO_STOCKS = tuple("""
360ONE ABB ABCAPITAL ADANIENSOL ADANIENT ADANIGREEN ADANIPORTS ADANIPOWER ALKEM AMBER AMBUJACEM ANGELONE
APLAPOLLO APOLLOHOSP ASHOKLEY ASIANPAINT ASTRAL ATHERENERG AUBANK AUROPHARMA AXISBANK BAJAJ-AUTO BAJAJFINSV BAJAJHLDNG
BAJFINANCE BANDHANBNK BANKBARODA BANKINDIA BDL BEL BHARATFORG BHARTIARTL BHEL BIOCON BLUESTARCO BOSCHLTD BPCL
BRITANNIA BSE CAMS CANBK CDSL CGPOWER CHOLAFIN CIPLA COALINDIA COCHINSHIP COFORGE COLPAL CONCOR CROMPTON
CUMMINSIND DABUR DELHIVERY DIVISLAB DIXON DLF DMART DRREDDY EICHERMOT ETERNAL FEDERALBNK FORCEMOT
FORTIS GAIL GLENMARK GMRAIRPORT GODFRYPHLP GODREJCP GODREJPROP GRASIM GVT&D HAL HAVELLS HCLTECH HDFCAMC
HDFCBANK HDFCLIFE HEROMOTOCO HINDALCO HINDPETRO HINDUNILVR HINDZINC HYUNDAI ICICIBANK ICICIGI ICICIPRULI
IDEA IDFCFIRSTB IEX INDHOTEL INDIANB INDIGO INDUSINDBK INDUSTOWER INFY INOXWIND IOC IREDA IRFC ITC JINDALSTEL
JIOFIN JSWENERGY JSWSTEEL JUBLFOOD KALYANKJIL KAYNES KEI KFINTECH KOTAKBANK KPITTECH LAURUSLABS LICHSGFIN
LICI LODHA LT LTF LTM LUPIN M&M MAHABANK MANAPPURAM MANKIND MARICO MARUTI MAXHEALTH MAZDOCK MCX MFSL MOTHERSON
MOTILALOFS MPHASIS MUTHOOTFIN NAM-INDIA NATIONALUM NAUKRI NBCC NESTLEIND NHPC NMDC NTPC NYKAA OBEROIRLTY
OFSS OIL ONGC PAGEIND PATANJALI PAYTM PERSISTENT PETRONET PFC PGEL PHOENIXLTD PIDILITIND PIIND PNB PNBHOUSING
POLICYBZR POLYCAB POWERGRID POWERINDIA PREMIERENE PRESTIGE RADICO RBLBANK RECLTD RELIANCE RVNL SAGILITY SAIL SBICARD
SBILIFE SBIN SHREECEM SHRIRAMFIN SIEMENS SOLARINDS SONACOMS SRF SUNPHARMA SUPREMEIND SUZLON SWIGGY TATACONSUM
TATAELXSI TATAPOWER TATASTEEL TCS TECHM TIINDIA TITAN TMPV TORNTPHARM TRENT TVSMOTOR ULTRACEMCO UNIONBANK
UNITDSPR UNOMINDA UPL VBL VEDL VMM VOLTAS WAAREEENER WIPRO YESBANK ZYDUSLIFE
""".split())

STOCK_SPOTS = {symbol: f"NSE:{symbol}-EQ" for symbol in FNO_STOCKS}
SPOT_SYMBOLS = tuple(INDEX_SPOTS.values()) + tuple(STOCK_SPOTS.values())
DISPLAY_BY_SPOT = {value: key for key, value in {**INDEX_SPOTS, **STOCK_SPOTS}.items()}


def desk_underlying(symbol: str) -> str | None:
    """The underlying name behind a spot, an equity or a futures symbol.

    The auction desk watches index FUTURES rather than index spots, because an
    index spot streams no volume at all -- NIFTY50-INDEX, NIFTYBANK-INDEX and
    SENSEX-INDEX each recorded exactly 0 traded volume across a full session,
    so cumulative delta, footprint and absorption are all undefined on them.
    Options are still keyed to the spot, so the desk resolves both forms to a
    common underlying name.

        NSE:NIFTY26AUGFUT  -> NIFTY
        NSE:ICICIBANK-EQ   -> ICICIBANK
        NSE:NIFTY50-INDEX  -> NIFTY
    """
    import re

    if symbol in DISPLAY_BY_SPOT:
        return DISPLAY_BY_SPOT[symbol]
    body = symbol.split(":", 1)[-1]
    if body.endswith("-EQ"):
        return body[:-3]
    match = re.match(r"^([A-Z&\-]+?)\d{2}[A-Z]{3}FUT$", body)
    return match.group(1) if match else None
